version: '3.8'

services:
  rerum:
    build:
      context: C:\Users\supra\OneDrive\PSD project\rerum_server_nodejs
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: "mongodb://mongo:27017/rerum"

  tiny:
    build:
      context: C:\Users\supra\OneDrive\PSD project\TinyNode
    ports:
      - "4000:4000"

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
